name: Portfolio CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: check project files
        run: ls -la

      - name: project info
      - run: echo "Portfolio Manager CI running!"

      - name: Show date
      - run: date
